- task: AzurePowerShell@3
  displayName: 'Update StreamAnalytics with Powershell'
  inputs:
    azureSubscription: 'Azure'
    scriptType: 'FilePath'
    scriptPath: './StreamAnalytics/Update-StreamAnalyticsIOQueries.ps1'
    errorActionPreference: 'stop'
    failOnStandardError: false
    azurePowerShellVersion: 'latestVersion'